require 'jira_cli'
require 'ap'
require 'yaml'

EXAMPLES = [
  "--action addAttachment --issue \"ZATTACH-1\" --file \"-\" --name \"dataFromStandardInput.txt\" --findReplace \"xxx:yyy\"",
  "--action addAttachment --issue \"ZATTACH-1\" --file \"src/itest/resources/binary.bin\" --verbose",
  "--action addAttachment --issue \"ZATTACH-1\" --file \"src/itest/resources/data.txt\" --findReplace \"xxx:yyy\" --verbose",
  "--action addAttachment --issue \"ZATTACH-1\" --file \"src/itest/resources/data.txt\" --name \"data\"",
  "--action addAttachment --issue \"ZATTACH-1\" --file \"src/itest/resources/empty.txt\"",
  "--action addAttachment --issue \"ZATTACH-1\" --file \"src/itest/resources/large.zip\"",
  "--action addAttachment --issue \"ZATTACH-1\" --file \"src/itest/resources/Special name #&?\"",
  "--action addAttachment --issue \"ZJIRACLI-3\" --file \"src/itest/resources/data.txt\"",
  "--action addAttachment --issue \"ZRUNNER-1\" --file \"src/itest/resources/data.txt\"",
  "--action addAttachments --issue \"ZATTACH-1\" --file \"src/itest/resources\" --regex \"((data)|(empty)).*\" --recursive",
  "--action addComment --issue \"ZCLICLONE-1\" --comment \"my comment\" --role \"Developers\"",
  "--action addComment --issue \"ZCLICLONE-4\" --comment \"my comment\"",
  "--action addComment --issue \"ZCLICLONE-4\" --comment \"my group restricted comment\" --group \"jira-users\"",
  "--action addComment --issue \"ZCLICLONE-4\" --comment \"my role restricted comment\" --role \"Developers\"",
  "--action addComment --issue \"ZJIRACLI-3\" --file \"src/itest/resources/data.txt\" --findReplace \"xxx:yyy\"",
  "--action addComment --issue \"ZSUB-3\" --comment \"\n                resolution: %original_resolution%\n                resolutiondate: %original_resolutiondate%\n                resolution_date: %original_resolution_date%\n                resolution_date with format: %original_resolution_date(yyyy-MM-dd HH:mm:ss)%\n                now with format: %now(yyyy-MM-dd HH:mm:ss)%\n            \" --dateFormat \"yyyy-MM-dd HH:mm:ss\"",
  "--action addComponent --project \"ZCOMP\" --name \"C1\" --lead \"automation\" --description \"C1 description\" --defaultAssignee \"COMPONENT_LEAD\"",
  "--action addComponent --project \"ZCOMP\" --name \"C2\" --lead \"automation\" --description \"C2 description\" --defaultAssignee \"COMPONENT_LEAD\"",
  "--action addComponent --project \"ZEXPORT2\" --name \"C1\" --description \"C1 description\"",
  "--action addComponent --project \"zjiracli\" --name \"C1\" --description \"a generic description\"",
  "--action addComponent --project \"zjiracli\" --name \"C1\" --description \"a generic description\" --replace",
  "--action addComponent --project \"zjiracli\" --name \"C2\" --lead \"developer\" --description \"a generic description\" --defaultAssignee \"COMPONENT_LEAD\"",
  "--action addComponent --project \"zjiracli\" --name \"swap2\" --description \"a generic description\"",
  "--action addCustomField --field \"zzz_Number Field\" --type \"com.atlassian.jira.plugin.system.customfieldtypes:float\" --continue --jql \"com.atlassian.jira.plugin.system.customfieldtypes:exactnumber\"",
  "--action addCustomField --field \"zzz_Radio Buttons\" --type \"com.atlassian.jira.plugin.system.customfieldtypes:radiobuttons\" --continue",
  "--action addCustomField --field \"zzz_Select List (single choice)\" --type \"com.atlassian.jira.plugin.system.customfieldtypes:multiselect\" --continue",
  "--action addGroup --group \"Testgroup1\" --preserveCase",
  "--action addLabels --issue \"ZJIRACLI-8\" --labels \"addLabel1 addLabel2\"",
  "--action addProjectRoleActors --project \"zjiracli\" --role \"users\" --userId \"user, admin\"",
  "--action addProjectRoleActors --project \"ZROLES\" --role \"administrators\" --userId \"project-admin\"",
  "--action addProjectRoleActors --project \"ZROLES\" --role \"users\" --userId \"user, admin\"",
  "--action addProjectRole --name \"zAdd project role test\" --description \"addProjectRole test\"",
  "--action addRemoteLink --issue \"ZLINKS-1\" --name \"addRemoteLinkUrl\" --url \"https://google.com\"",
  "--action addTransition --workflow \"zjiracliworkflow_new\" --name \"test 1\" --description \"Transition for testing\" --step \"1\"",
  "--action addTransition --workflow \"zjiracliworkflow_new\" --name \"test 2\" --description \"Transition for testing\" --step \"1\" --transition \"3\" --screen \"Default Screen\"",
  "--action addTransition --workflow \"zjiracliworkflow_new\" --name \"test 3\" --description \"Transition for testing\" --step \"1\" --screen \"12326\"",
  "--action addTransition --workflow \"zjiracliworkflow_new\" --name \"test 4\" --description \"Transition for testing\" --step \"1\" --screen \"FIELDCONF: Software Development Default Issue Screen\"",
  "--action addTransition --workflow \"zjiracliworkflow_new\" --name \"test 9\" --description \"Transition for testing\" --step \"3\"",
  "--action addUserToGroup --userId \"Testuser3\" --group \"testgroup2\" --autoGroup",
  "--action addUser --userId \"automation\" --userEmail \"testuser@x.com\"",
  "--action addUser --userId \"testuser1\" --userFullName \"Test User1\" --userEmail \"testuser1@x.com\" --userPassword \"\"",
  "--action addUser --userId \"testuser2\" --userFullName \"Special User 2\" --userEmail \"testuser2@x.com\"",
  "--action addUser --userId \"Testuser3\" --userEmail \"testuser3@x.com\" --preserveCase",
  "--action addVersion --project \"ZEXPORT2\" --name \"V1\" --description \"V1 description\"",
  "--action addVersion --project \"zjiracli for automated testing\" --name \"V2\" --date \"5/30/15\" --startDate \"9/30/14\" --after \"V1\" --description \"V2 description\"",
  "--action addVersion --project \"zjiracli for automated testing\" --name \"With Blanks\"",
  "--action addVersion --project \"zjiracli\" --name \"V1\"",
  "--action addVersion --project \"zjiracli\" --version \"V2\" --date \"5/30/15\" --description \"V2 description\" --replace",
  "--action addVersion --project \"ZRUNNER\" --name \"V1\"",
  "--action addVersion --project \"ZRUNNER\" --name \"V2\"",
  "--action addVote --issue \"ZVOTEWATCH-1\" --user \"developer\" --password \"asDeVqeTwsjtr4GnyKwf\"",
  "--action addWatchers --issue \"ZCLICLONE-4\" --userId \"user, developer\"",
  "--action addWatchers --issue \"ZSUB-1\" --userId \"admin, developer\"",
  "--action addWatchers --issue \"ZVOTEWATCH-1\" --userId \"invalid1, invalid2\" --continue",
  "--action addWatchers --issue \"ZVOTEWATCH-1\" --userId \"user, developer\"",
  "--action addWork --issue \"ZCLICLONE-4\" --timeSpent \"1h\" --autoAdjust",
  "--action addWork --issue \"ZWORK-1\" --timeSpent \"1d 1h\" --date \"1/02/11 9:00 a\"",
  "--action addWork --issue \"ZWORK-1\" --timeSpent \"3h 30m\" --comment \"My work log entry\" --role \"Developers\" --group \"jira-users\"",
  "--action addWork --issue \"ZWORK-1\" --timeSpent \"3h 30m\" --date \"2011-01-01\" --dateFormat \"yyyy-MM-dd\" --group \"jira-users\"",
  "--action addWork --issue \"ZWORK-1\" --timeSpent \"3h 30m\" --estimate \"3w\"",
  "--action addWork --issue \"ZWORK-1\" --timeSpent \"3m\" --date \"2011-01-01\"",
  "--action addWork --issue \"ZWORK-1\" --timeSpent \"3m\" --date \"2011-01-01 22:33:01\"",
  "--action addWork --issue \"ZWORK-1\" --timeSpent \"5\" --userId \"developer\"",
  "--action addWork --issue \"ZWORK-2\" --timeSpent \"2h\"",
  "--action archiveVersion --project \"zjiracli\" --version \"V1\"",
  "--action assignIssue --issue \"ZJIRACLI-5\" --userId \"\"",
  "--action assignIssue --issue \"ZJIRACLI-5\" --userId \"automation\"",
  "--action assignIssue --issue \"ZJIRACLI-5\" --userId \"@default\"",
  "--action cloneIssue --issue \"ZATTACH-1\" --copyAttachments",
  "--action cloneIssue --issue \"ZCLICLONE-3\"",
  "--action cloneIssue --issue \"ZCLICLONE-4\" --parent \"ZCLICLONE-2\" --copySubtaskEstimates --copyLinks --copyWatchers --copyComments --useParentVersions --fieldExcludes \"custom-multi-select,custom three\" --quiet",
  "--action cloneIssue --issue \"ZJIRACLI-3\" --description \"clone description\"",
  "--action cloneIssue --issue \"ZJIRACLI-3\" --summary \"clone summary\" --comment \"comment for cloned issue\"",
  "--action cloneIssue --issue \"ZJIRACLI-3\" --summary \"clone summary\" --date \"2013-12-30\" --dateFormat \"yyyy-MM-dd\"",
  "--action cloneIssue --issue \"ZLINKS-1\" --summary \"cloneThis is content.\" --link \"Cloners\"",
  "--action cloneIssue --project \"ZCLICLONE\" --issue \"ZCLICLONE-1\"",
  "--action cloneIssue --project \"ZCLICLONE\" --issue \"ZCLICLONE-1\" --copyLinks",
  "--action cloneIssue --project \"ZCLICLONEX\" --issue \"ZCLICLONE-1\" --copySubtaskEstimates --copyLinks --copyWatchers --copyComments",
  "--action cloneIssues --copyAttachments --copySubtasks --jql \"key = ZATTACH-1\"",
  "--action cloneIssues --jql \"issue = ZCLICLONE-1\" --copySubtasks",
  "--action cloneIssues --project \"ZCLICLONEX\" --jql \"project = ZCLICLONE and issuetype = bug\" --autoVersion --autoComponent",
  "--action cloneIssues --project \"ZCLICLONEX\" --type \"improvement\" --jql \"project = ZCLICLONE and issuetype = bug\"",
  "--action cloneIssues --project \"zjiracliA\" --jql \"project = zjiracli and issuetype = bug\"",
  "--action cloneIssues --project \"zjiracliA\" --type \"improvement\" --jql \"project = zjiracli and issuetype = bug\"",
  "--action cloneIssues --toProject \"ZRUNNERC\" --description \"Bulk clone example\" --search 'project = ZRUNNER and summary ~ \"volume-*\"'",
  "--action cloneIssues --type \"task\" --jql \"project = ZCLICLONE and issuetype = bug\"",
  "--action cloneIssues --type \"task\" --jql \"project = zjiracli and issuetype = bug\"",
  "--action cloneProject --project \"Template\" --toProject \"zjiracli\" --lead \"automation\" --name \"zjiracli for automated testing\" --defaultAssignee \"unassigned\"",
  "--action cloneProject --project \"ZAGILE\" --toProject \"ZAGILEC\" --cloneIssues",
  "--action cloneProject --project \"ZATTACH\" --toProject \"ZATTACH2\" --cloneIssues --copyAttachments --copySubtasks",
  "--action cloneProject --project \"ZCLICLONEB\" --issueTypeScheme \"Default Issue Type Scheme\" --issueTypeScreenScheme \"Default Issue Type Screen Scheme\" --permissionScheme \"Default Permission Scheme\" --toProject \"ZCLICLONEY\"",
  "--action cloneProject --project \"ZCLICLONE\" --issueTypeScheme \"Default Issue Type Scheme\" --issueTypeScreenScheme \"Default Issue Type Screen Scheme\" --permissionScheme \"Default Permission Scheme\" --toProject \"ZCLICLONEX\"",
  "--action cloneProject --project \"ZCLICLONES\" --issueTypeScheme \"Default Issue Type Scheme\" --issueTypeScreenScheme \"Default Issue Type Screen Scheme\" --permissionScheme \"Default Permission Scheme\" --toProject \"ZCLICLONET\"",
  "--action cloneProject --project \"zjiracliC\" --toProject \"zjiracliD\"",
  "--action cloneProject --project \"zjiracli\" --jql \"type = 'bug'\" --toProject \"zjiracliB\" --issueSecurityScheme \"test restrictions\" --copyVersions --copyComponents --copyRoleActors --cloneIssues --copyAttachments --copySubtasks --continue",
  "--action cloneProject --project \"zjiracli\" --toProject \"zjiracliA\" --name \"ZcloneNameA\"",
  "--action cloneProject --project \"zjiracli\" --toProject \"zjiracliC\" --cloneIssues --jql \"issuetype = bug\" --autoVersion --debug",
  "--action copyAttachments --issue \"ZATTACH-1\" --toIssue \"ZATTACH-2\"",
  "--action copyAttachments --issue \"ZATTACH-1\" --toIssue \"ZATTACH-3\" --name \"data.txt\"",
  "--action copyComponent --project \"ZCOMP\" --toProject \"ZCOMP2\" --component \"C1\"",
  "--action copyComponent --project \"zjiracli\" --component \"C1\" --name \"C3First\" --description \"override description\"",
  "--action copyComponents --project \"ZCOMP\" --toProject \"ZCOMP2\" --replace",
  "--action copyComponents --project \"zjiracli\" --toProject \"zjiracliX\"",
  "--action copyComponents --project \"zjiracli\" --toProject \"zjiracliX\" --components \"C1, C2\" --replace",
  "--action copyFieldValue --issue \"ZJIRACLI-10\" --field \"custom1\" --field2 \"custom-versions\" --asVersion --autoVersion",
  "--action copyFieldValue --issue \"ZJIRACLI-10\" --toIssue \"ZJIRACLI-11\" --field \"custom1\"",
  "--action copyFieldValue --issue \"ZJIRACLI-10\" --toIssue \"ZJIRACLI-11\" --field \"fixVersions\" --field2 \"custom-versions\" --asVersion",
  "--action copyFieldValue --issue \"ZJIRACLI-10\" --toIssue \"ZJIRACLI-11\" --field \"summary\" --field2 \"custom2\"",
  "--action copyProjectRoleActors --project \"ZROLES\" --toProject \"ZROLESX\"",
  "--action copyVersion --project \"zjiracliA\" --version \"V1\" --name \"newV1\"",
  "--action copyVersion --project \"zjiracli\" --toProject \"zjiracliA\" --name \"V1\"",
  "--action copyVersion --project \"zjiracli\" --toProject \"zjiracliA\" --name \"V2\" --after -1",
  "--action copyVersion --project \"zjiracli\" --toProject \"zjiracliA\" --version \"V1\" --description \"replaced description\" --startDate \"9/30/14\" --replace",
  "--action copyVersions --project \"zjiracli\" --toProject \"zjiracliC\" --replace",
  "--action copyWorkflow --workflow \"jira\" --name \"zjiracliworkflow_new\" --description \"Copy of jira for jiracliworkflow test\"",
  "--action createBoard --name \"ZAGILE\" --type \"kanban\" --project \"ZAGILE\"",
  "--action createBoard --name \"ZAGILE\" --type \"scrum\" --project \"ZAGILE\"",
  "--action createFilter --name \"ZFILTER2\" --description \"ZFILTER2 description\" --jql \"project = ZFILTER\" --favorite",
  "--action createIssue --parent \"ZSUB-1\" --type \"Sub-task\" --summary \"subtask2: %parent_summary%\"",
  "--action createIssue --project \"ZAGILE\" --type \"Epic\" --summary \"Epic issue\" --field \"Epic Name\" --value \"Epic1\"",
  "--action createIssue --project \"ZAGILE\" --type \"Story\" --summary \"Story issue\" --field \"Epic Link\" --value \"ZAGILE-1\"",
  "--action createIssue --project \"ZATTACH\" --type \"bug\" --summary \"Copy attachments target\"",
  "--action createIssue --project \"ZATTACH\" --type \"bug\" --summary \"For attachments\"",
  "--action createIssue --project \"ZATTACH\" --type \"Sub-task\" --parent \"ZATTACH-1\" --summary \"Subtask with attachments\"",
  "--action createIssue --project \"ZCLICLONE\" --parent \"ZCLICLONE-1\" --summary \"Subtask 1\" --type \"Sub-task\"",
  "--action createIssue --project \"ZCLICLONE\" --parent \"ZCLICLONE-1\" --summary \"Subtask 2\" --type \"Sub-task2\" --originalEstimate \"1d\" --custom \"testcase1:xxx,custom three:333\"",
  "--action createIssue --project \"ZCLICLONE\" --type \"bug\" --summary \"Summary\" --affectsVersions \"V1\" --fixVersions \"V1,V2\" --components \"C2,C1\" --field \"custom-versions\" --values \"V2, V1\" --autoVersion --autoComponent --field2 \"custom-user-picker\" --values2 \"automation\"",
  "--action createIssue --project \"ZCOMP\" --type \"bug\" --summary \"test\" --components \"auto1,auto2\" --autoComponent",
  "--action createIssue --project \"zcustom\" --type \"bug\" --summary \"cascade issue\" --custom \"custom1:xxxx\" --field \"custom-cascade-select\" --values \"1,A\" --asCascadeSelect",
  "--action createIssue --project \"zcustom\" --type \"bug\" --summary \"cascade issue\" --custom \"custom1:xxxx\" --field \"custom-cascade-select\" --values \"1,A\" --field2 \"custom-multi-select\" --values2 \"s1\" --asCascadeSelect",
  "--action createIssue --project \"zcustom\" --type \"bug\" --summary \"cascade issue\" --field \"custom-cascade-select\" --values \"1,A\" --asCascadeSelect",
  "--action createIssue --project \"zcustom\" --type \"bug\" --summary \"checkbox\" --field \"custom-multi-checkbox\" --values \"check1,check2\"",
  "--action createIssue --project \"zcustom\" --type \"Story\" --summary \"json\" --custom \"{\\\"custom-date\\\":{\\\"offset\\\":\\\"-30\\\",\\\"value\\\":\\\"%now%\\\"},\\\"Story Points\\\":{\\\"offset\\\":-4.2,\\\"value\\\":\\\"10.1\\\"}}\" --date \"{\\\"offset\\\":5,\\\"value\\\":\\\"%now%\\\"}\" --dateFormat \"yyyy-MM-dd\"",
  "--action createIssue --project \"zcustom\" --type \"Story\" --summary \"json\" --custom \"{\\\"custom-datetime\\\":{\\\"offset\\\":15,\\\"value\\\":\\\"%now%\\\"},\\\"custom-date\\\":{\\\"offset\\\":\\\"15\\\",\\\"value\\\":\\\"2015-05-01\\\"},\\\"Story Points\\\":{\\\"offset\\\":\\\"5\\\",\\\"value\\\":\\\"10\\\"}}\" --date \"%now%\" --dateFormat \"yyyy-MM-dd HH:mm:ss\"",
  "--action createIssue --project \"zcustom\" --type \"story\" --summary \"mutli issue\" --field \"custom-multi-select\" --values \"s1,s2,s3\" --field2 \"testcase2\" --values2 \"No\" --custom \"testcase1:zzzzzzzzzz,Story Points:99.1\"",
  "--action createIssue --project \"ZFIELDS\" --file \"src/itest/resources/data.txt\" --type \"Bug\" --summary \"original summary\" --assignee \"automation\" --environment \"original environment\" --fixVersions \"V1,V2\" --components \"C1\" --autoVersion --autoComponent",
  "--action createIssue --project \"ZFIELDS\" --file \"src/itest/resources/data.txt\" --type \"Bug\" --summary \"This is content.\" --assignee \"automation\" --environment \"x12345\"",
  "--action createIssue --project \"ZFIELDS\" --type \"Sub-task\" --summary \"This is content.\" --parent \"ZFIELDS-1\"",
  "--action createIssue --project \"ZHISTORY\" --type \"task\" --summary \"Initial summary\"",
  "--action createIssue --project \"zjiracliB\" --type \"bug\" --summary \"secured issue\" --security \"developer-role\"",
  "--action createIssue --project \"zjiracli\" --file \"src/itest/resources/data.txt\" --type \"Bug\" --summary \"This is content.\" --assignee \"automation\" --lookup --date \"\" --field \"custom-multi-select\" --values \"s1,s2,s3\" --originalEstimate \"20m\"",
  "--action createIssue --project \"zjiracli\" --file \"target/output/jiracli/createIssueLongDescription.txt\" --type \"task\" --summary \"Long description\"",
  "--action createIssue --project \"zjiracli for automated testing\" --type \"task\" --summary \"This is content.\" --assignee \"automation\" --comment \"Added after create\"",
  "--action createIssue --project \"zjiracli\" --type \"Bug\" --summary \"This is content.\" --labels \"label1\"",
  "--action createIssue --project \"zjiracli\" --type \"Bug\" --summary \"This is content.\" --labels \"xxx\"",
  "--action createIssue --project \"zjiracli\" --type \"Sub-task\" --summary \"This is content.\" --parent \"ZJIRACLI-1\"",
  "--action createIssue --project \"zjiracli\" --type \"task\" --summary \"This is content.\"",
  "--action createIssue --project \"zjiracli\" --type \"task\" --summary \"This is content.\" --field \"custom1\" --values \"V1copy\" --fixVersions \"V1\"",
  "--action createIssue --project \"zjiracliX\" --type \"bug\" --summary \"This is content.\"",
  "--action createIssue --project \"zjiracliX\" --type \"Bug\" --summary \"This is content.\" --description \"a generic description\"",
  "--action createIssue --project \"zlinks\" --type \"Bug\" --summary \"This is content.\"",
  "--action createIssue --project \"zlinks\" --type \"Sub-task\" --summary \"This is content.\" --parent \"ZLINKS-1\"",
  "--action createIssue --project \"ZRUNNER\" --type \"Bug\" --summary \"This is content\"",
  "--action createIssue --project \"ZSUB\" --type \"bug\" --summary \"Summary\"",
  "--action createIssue --project \"ZSUB\" --type \"bug\" --summary \"Summary\" --description \"Description\" --environment \"Environment\" --affectsVersions \"V1\" --fixVersions \"V1,V2\" --components \"C1,C2\" --autoVersion --autoComponent --assignee \"automation\" --labels \"label1 label2\" --security \"developer-role\" --field \"custom1\" --value \"Custom1\" --field2 \"custom2\" --values2 \"Custom2\"",
  "--action createIssue --project \"ZSUPPORT\" --type \"bug\" --priority \"Major\" --summary \"Summary\"",
  "--action createIssue --project \"zuser\" --type \"Bug\" --summary \"This is content\" --assignee \"automation\"",
  "--action createIssue --project \"zvotewatch\" --type \"Bug\" --summary \"summary text\"",
  "--action createIssue --project \"zwork\" --type \"Bug\" --summary \"This is content\"",
  "--action createIssue --type \"Sub-task\" --summary \"This is content.\" --parent \"249564\"",
  "--action createOrUpdateIssue --project \"zjiracli\" --type \"bug\" --summary \"CreateOrUpdate - updated\" --jql \"project = zjiracli and summary ~ 'CreateOrUpdate: 1501339484158'\"",
  "--action createOrUpdateIssue --project \"zjiracli\" --type \"task\" --summary \"createOrUpdate: 1501339484158\" --jql \"custom1 ~ UNDEFINED-TEXT-DATA\"",
  "--action createProject --project \"ZAGILE\" --name \"zjiracliagile\" --description \"GINT test: jiracliagile\" --lead \"automation\" --template \"Template\"",
  "--action createProject --project \"ZATTACH\" --name \"zjiracliattachments\" --description \"GINT test: jiracliattachments\" --lead \"automation\" --template \"Template\"",
  "--action createProject --project \"ZCLICLONEB\" --lead \"automation\" --type \"business\" --template \"Task management\" --issueTypeScheme \"Default Issue Type Scheme\" --issueTypeScreenScheme \"Default Issue Type Screen Scheme\" --permissionScheme \"Default Permission Scheme\"",
  "--action createProject --project \"ZCLICLONE\" --lead \"automation\" --template \"Template\"",
  "--action createProject --project \"ZCLICLONES\" --lead \"automation\" --template \"Basic\" --issueTypeScheme \"Default Issue Type Scheme\" --issueTypeScreenScheme \"Default Issue Type Screen Scheme\" --permissionScheme \"Default Permission Scheme\"",
  "--action createProject --project \"ZCOMP2\" --name \"zjiraclicomponents2\" --description \"GINT test: jiraclicomponents\" --lead \"automation\" --template \"Template\"",
  "--action createProject --project \"ZCOMP\" --name \"zjiraclicomponents\" --description \"GINT test: jiraclicomponents\" --lead \"automation\" --template \"Template\"",
  "--action createProject --project \"ZCUSTOM\" --name \"zjiraclicustom\" --description \"GINT test: jiraclicustom\" --lead \"automation\" --template \"Template\"",
  "--action createProject --project \"ZEXPORT2\" --name \"zjiracliexport2\" --description \"GINT test: jiracliexport2\" --lead \"automation\" --template \"Template\"",
  "--action createProject --project \"ZEXPORT\" --name \"zjiracliexport\" --description \"GINT test: jiracliexport\" --lead \"automation\" --template \"Template\"",
  "--action createProject --project \"ZFIELDS\" --name \"zjiraclifields\" --description \"GINT test: jiraclifields\" --lead \"automation\" --template \"Template\"",
  "--action createProject --project \"ZFILTER\" --name \"zjiraclifilter\" --description \"GINT test: jiraclifilter\" --lead \"automation\" --template \"Template\"",
  "--action createProject --project \"ZHISTORY\" --name \"zjiraclihistory\" --description \"GINT test: jiraclihistory\" --lead \"automation\" --template \"Template\"",
  "--action createProject --project \"zjiracliX\" --template \"Template\" --workflowScheme \"\" --issueTypeScheme \"Default Issue Type Scheme\" --issueTypeScreenScheme \"Default Issue Type Screen Scheme\" --permissionScheme \"Default Permission Scheme\" --lead \"automation\" --name \"zjiracliX for automated testing\"",
  "--action createProject --project \"ZLINKS\" --name \"zjiraclilinks\" --description \"GINT test: jiraclilinks\" --lead \"automation\" --template \"Template\"",
  "--action createProject --project \"ZPROJECT\" --name \"zjiracliproject\" --description \"GINT test: jiracliproject\" --lead \"automation\" --template \"Template\" --category \"another\"",
  "--action createProject --project \"ZPROJECTX\" --template \"Template\" --lead \"developer\" --workflowScheme \"\" --notificationScheme \"\" --category \"another\"",
  "--action createProject --project \"ZPROJECTZ\" --template \"Kanban software development\" --lead \"admin\"",
  "--action createProject --project \"ZROLES\" --name \"zjiracliroles\" --description \"GINT test: jiracliroles\" --lead \"automation\" --template \"Template\"",
  "--action createProject --project \"ZROLESX\" --name \"zjiraclirolesX\" --description \"GINT test: jiracliroles\" --lead \"automation\" --template \"Template\"",
  "--action createProject --project \"ZRUNNERC\" --name \"zjiraclirunnerC\" --description \"GINT test: jiraclirunner\" --lead \"automation\" --template \"Template\"",
  "--action createProject --project \"ZRUNNER\" --name \"zjiraclirunner\" --description \"GINT test: jiraclirunner\" --lead \"automation\" --template \"Template\"",
  "--action createProject --project \"ZSUB\" --name \"zjiraclisub\" --description \"GINT test: jiraclisub\" --lead \"automation\" --template \"Template\" --issueSecurityScheme \"test restrictions\" --category \"standard\"",
  "--action createProject --project \"ZSUPPORT\" --name \"zjiraclisupport\" --description \"GINT test: jiraclisupport\" --lead \"automation\" --template \"Template\" --issueSecurityScheme \"test restrictions\" --category \"standard\"",
  "--action createProject --project \"ZUSER\" --name \"zjiracliuser\" --description \"GINT test: jiracliuser\" --lead \"automation\" --template \"Template\"",
  "--action createProject --project \"ZVOTEWATCH\" --name \"zjiraclivotewatch\" --description \"GINT test: jiraclivotewatch\" --lead \"automation\" --template \"Template\"",
  "--action createProject --project \"ZWORK\" --name \"zjiracliwork\" --description \"GINT test: jiracliwork\" --lead \"automation\" --template \"Template\"",
  "--action deleteBoard --board \"NOT_FOUND\" --continue",
  "--action deleteBoard --board \"ZAGILE\" --deleteFilter",
  "--action deleteBoard --id \"1228\" --deleteFilter",
  "--action deleteBoard --id 1234567890 --continue",
  "--action deleteComponent --project \"zjiracli\" --component 71357",
  "--action deleteComponent --project \"zjiracli\" --component \"swap1\" --toComponent \"swap2\"",
  "--action deleteComponent --project \"zjiracli\" --name \"auto1\"",
  "--action deleteComponent --project \"zjiracli\" --name \"auto2\"",
  "--action deleteComponent --project \"zjiracliX\" --component \"C2\"",
  "--action deleteComponent --project \"zjiracliX\" --component \"C3\"",
  "--action deleteComponent --project \"zjiracliX\" --name \"C1\"",
  "--action deleteComponent --project \"zjiracliX\" --name \"C1\" --continue",
  "--action deleteFieldConfiguration --id \"1234556780\" --continue",
  "--action deleteFieldConfigurationScheme --id \"1234556780\" --continue",
  "--action deleteFilter --filter \"NOT_FOUND\" --continue",
  "--action deleteFilter --id 1234567890 --continue",
  "--action deleteFilter --id \"24903\"",
  "--action deleteIssue --issue \"ZJIRACLI-1\"",
  "--action deleteIssue --issue \"ZJIRACLI-1\" --continue",
  "--action deleteIssueSecurityScheme --id \"1234556780\" --continue",
  "--action deleteIssueTypeScheme --id \"1234556780\" --continue",
  "--action deleteIssueTypeScreenScheme --id \"1234556780\" --continue",
  "--action deleteLink --issue \"249453\" --toIssue \"249454\" --link \"10011\"",
  "--action deleteLink --issue \"ZLINKS-1\" --toIssue \"ZLINKS-3\" --link \"duplicates\"",
  "--action deleteNotificationScheme --id \"1234556780\" --continue",
  "--action deletePermissionScheme --id \"1234556780\" --continue",
  "--action deleteProject --project \"NOT_FOUND\" --continue",
  "--action deleteProject --project \"ZAGILEC\" --continue",
  "--action deleteProject --project \"ZAGILE\" --continue",
  "--action deleteProject --project \"ZATTACH2\" --continue",
  "--action deleteProject --project \"ZATTACH\" --continue",
  "--action deleteProject --project \"ZCLICLONEB\" --continue",
  "--action deleteProject --project \"ZCLICLONE\" --continue",
  "--action deleteProject --project \"ZCLICLONES\" --continue",
  "--action deleteProject --project \"ZCLICLONET\" --continue",
  "--action deleteProject --project \"ZCLICLONEX\" --continue",
  "--action deleteProject --project \"ZCLICLONEY\" --continue",
  "--action deleteProject --project \"ZCLICLONEZ\" --continue",
  "--action deleteProject --project \"ZCOMP2\" --continue",
  "--action deleteProject --project \"ZCOMP\" --continue",
  "--action deleteProject --project \"ZCUSTOM\" --continue",
  "--action deleteProject --project \"ZEXPORT2\" --continue",
  "--action deleteProject --project \"ZEXPORT2E\" --continue",
  "--action deleteProject --project \"ZEXPORT\" --continue",
  "--action deleteProject --project \"ZFIELDS\" --continue",
  "--action deleteProject --project \"ZFILTER\" --continue",
  "--action deleteProject --project \"ZHISTORY\" --continue",
  "--action deleteProject --project \"ZIMPORT\" --continue",
  "--action deleteProject --project \"ZJIRACLIA\" --continue",
  "--action deleteProject --project \"ZJIRACLIB\" --continue",
  "--action deleteProject --project \"ZJIRACLIC\" --continue",
  "--action deleteProject --project \"ZJIRACLI\" --continue",
  "--action deleteProject --project \"ZJIRACLID\" --continue",
  "--action deleteProject --project \"ZJIRACLIE\" --continue",
  "--action deleteProject --project \"ZJIRACLIX\" --continue",
  "--action deleteProject --project \"ZLINKS\" --continue",
  "--action deleteProject --project \"ZPROJECT\" --continue",
  "--action deleteProject --project \"ZPROJECTE\" --continue",
  "--action deleteProject --project \"ZPROJECTX\" --continue",
  "--action deleteProject --project \"ZPROJECTZ\" --continue",
  "--action deleteProject --project \"ZROLES\" --continue",
  "--action deleteProject --project \"ZROLESX\" --continue",
  "--action deleteProject --project \"ZRUNNERC\" --continue",
  "--action deleteProject --project \"ZRUNNER\" --continue",
  "--action deleteProject --project \"ZSUB\" --continue",
  "--action deleteProject --project \"ZSUPPORT\" --continue",
  "--action deleteProject --project \"ZUSER\" --continue",
  "--action deleteProject --project \"ZVOTEWATCH\" --continue",
  "--action deleteProject --project \"ZWORK\" --continue",
  "--action deleteScreen --id \"1234556780\" --continue",
  "--action deleteScreenScheme --id \"1234556780\" --continue",
  "--action deleteVersion --project \"zjiracli\" --version \"auto2\" --continue",
  "--action deleteVersion --project \"zjiracli\" --version \"BAD\" --continue",
  "--action deleteVersion --project \"zjiracli\" --version \"swap1\" --affectsVersions \"swap2\" --fixVersions \"swap2\"",
  "--action deleteVersion --project \"zjiracli\" --version \"swap2\" --fixVersions \"swap3\" --autoVersion --verbose",
  "--action deleteVersion --project \"zjiracli\" --version \"swap3\"",
  "--action deleteVersion --project \"ZRUNNER\" --version \"auto1csv\"",
  "--action deleteWorkflow --name \"zjiracliworkflow\" --continue",
  "--action deleteWorkflow --name \"zjiracliworkflow_new\" --continue",
  "--action deleteWorkflowScheme --name \"zjiracliworkflow\" --continue",
  "--action exportData --project \"ZEXPORT2\" --exportType \"Participants\"",
  "--action exportData --project \"ZEXPORT2\" --file \"target/output/jiracliexport2/exportDataProject.txt\"",
  "--action exportSite",
  "--action exportWorkflow --file \"target/output/jiracliworkflow/exportWorkflow.txt\" --workflow \"jira\"",
  "--action getApplicationLinkList --regex \"(?i)((confluence)|(jira)).*\"",
  "--action getAttachment --issue \"ZATTACH-1\" --file \"target/output/jiracliattachments/binary.bin\" --verbose",
  "--action getAttachment --issue \"ZATTACH-1\" --file \"target/output/jiracliattachments/dataFromStandardInput.txt\" --findReplace \"xxx:yyy\" --verbose",
  "--action getAttachment --issue \"ZATTACH-1\" --file \"target/output/jiracliattachments/data.txt\" --findReplace \"xxx:yyy\"",
  "--action getAttachment --issue \"ZATTACH-1\" --file \"target/output/jiracliattachments/getAttachment2.txt\" --name \"data.txt\" --findReplace \"xxx:yyy\"",
  "--action getAttachment --issue \"ZATTACH-1\" --file \"target/output/jiracliattachments/large.zip\" --verbose",
  "--action getAttachment --issue \"ZATTACH-1\" --file \"target/output/jiracliattachments/Special name #&?\"",
  "--action getAttachmentList --issue \"ZATTACH-1\" --dateFormat \"yyyy-MM-dd HH:mm:ss:S\"",
  "--action getAttachmentList --issue \"ZATTACH-1\" --dateFormat \"yyyy-MM-dd 'special format' HH:mm:ss:S z\"",
  "--action getAvailableSteps --issue \"ZJIRACLI-3\"",
  "--action getBoardList",
  "--action getBoardList --regex \"ZAGILE.*\"",
  "--action getClientInfo",
  "--action getCommentList --issue \"ZCLICLONE-6\"",
  "--action getCommentList --issue \"ZJIRACLI-1\" --dateFormat \"yyyy-MM-dd\"",
  "--action getCommentList --issue \"ZSUB-3\" --limit 2",
  "--action getComments --issue \"ZJIRACLI-12\"",
  "--action getComments --issue \"ZLINKS-1\"",
  "--action getComponentList --project \"ZCOMP2\" --outputFormat 999",
  "--action getComponentList --project \"ZCOMP\" --outputFormat 999",
  "--action getComponentList --project \"zjiracli\" --file \"target/output/jiracli/getComponentList.txt\"",
  "--action getComponentList --project \"zjiracli\" --outputFormat 999",
  "--action getComponent --project \"zjiracli\" --component \"C2\"",
  "--action getComponent --project \"zjiracli\" --component \"C3\"",
  "--action getComponent --project \"zjiracli\" --component \"C3First\"",
  "--action getCustomFieldList",
  "--action getCustomFieldList --regex \"zzz_.*\"",
  "--action getFieldConfigurationList",
  "--action getFieldConfigurationList --options \"deleteEnabled\"",
  "--action getFieldConfigurationSchemeList",
  "--action getFieldConfigurationSchemeList --options \"deleteEnabled\"",
  "--action getFieldList",
  "--action getFieldList --regex \"customfield_.*\"",
  "--action getFieldValue --issue \"ZCUSTOM-1\" --field \"custom-cascade-select\"",
  "--action getFieldValue --issue \"ZCUSTOM-4\" --field \"custom-multi-select\"",
  "--action getFieldValue --issue \"ZCUSTOM-5\" --field \"custom-multi-checkbox\"",
  "--action getFieldValue --issue \"ZFIELDS-1\" --field \"custom1\"",
  "--action getFieldValue --issue \"ZFIELDS-1\" --field \"custom-datetime\" --dateFormat \"dd/MM/yyyy HH:mm:ss\"",
  "--action getFieldValue --issue \"ZFIELDS-1\" --field \"description\"",
  "--action getFieldValue --issue \"ZFIELDS-1\" --field \"environment\"",
  "--action getFieldValue --issue \"ZFIELDS-2\" --field \"custom1\"",
  "--action getFieldValue --issue \"ZFIELDS-2\" --field \"custom-multi-select\" --suppressId",
  "--action getFieldValue --issue \"ZFIELDS-2\" --field \"custom-multi-select\" --withId",
  "--action getFieldValue --issue \"ZFIELDS-3\" --field \"description\" --withId",
  "--action getFieldValue --issue \"ZFIELDS-3\" --field \"priority\" --withId",
  "--action getFieldValue --issue \"ZFIELDS-3\" --field \"reporter\" --withId",
  "--action getFieldValue --issue \"ZFIELDS-3\" --field \"summary\" --withId",
  "--action getFieldValue --issue \"ZFIELDS-3\" --field \"type\" --withId",
  "--action getFieldValue --issue \"ZJIRACLI-10\" --field \"custom-versions\" --asVersion",
  "--action getFieldValue --issue \"ZJIRACLI-11\" --field \"custom1\"",
  "--action getFieldValue --issue \"ZJIRACLI-11\" --field \"custom2\"",
  "--action getFieldValue --issue \"ZJIRACLI-11\" --field \"custom-versions\" --asVersion",
  "--action getFieldValue --issue \"ZJIRACLI-3\" --field \"affectsVersions\"",
  "--action getFieldValue --issue \"ZJIRACLI-3\" --field \"assignee\" --dateFormat \"d/MMM/yy\"",
  "--action getFieldValue --issue \"ZJIRACLI-3\" --field \"components\"",
  "--action getFieldValue --issue \"ZJIRACLI-3\" --field \"custom-labels\"",
  "--action getFieldValue --issue \"ZJIRACLI-3\" --field \"duedate\" --dateFormat \"d/MMM/yy\"",
  "--action getFieldValue --issue \"ZJIRACLI-3\" --field \"environment\"",
  "--action getFieldValue --issue \"ZJIRACLI-3\" --field \"fixversions\"",
  "--action getFieldValue --issue \"ZJIRACLI-3\" --field \"fixVersions\"",
  "--action getFieldValue --issue \"ZJIRACLI-3\" --field \"fixversions\" --dateFormat \"d/MMM/yy\"",
  "--action getFieldValue --issue \"ZJIRACLI-3\" --field \"parent\"",
  "--action getFieldValue --issue \"ZJIRACLI-3\" --field \"reporter\" --dateFormat \"d/MMM/yy\"",
  "--action getFieldValue --issue \"ZJIRACLI-3\" --field \"resolution\"",
  "--action getFieldValue --issue \"ZJIRACLI-3\" --field \"resolutionDate\" --dateFormat \"d/MMM/yy\"",
  "--action getFieldValue --issue \"ZJIRACLI-3\" --field \"resolution\" --dateFormat \"d/MMM/yy\"",
  "--action getFieldValue --issue \"ZJIRACLI-3\" --field \"summary\"",
  "--action getFieldValue --issue \"ZJIRACLI-5\" --field \"10010\"",
  "--action getFieldValue --issue \"ZJIRACLI-5\" --field \"assignee\"",
  "--action getFieldValue --issue \"ZJIRACLI-5\" --field \"currentESTIMATE\"",
  "--action getFieldValue --issue \"ZJIRACLI-5\" --field \"custom1\"",
  "--action getFieldValue --issue \"ZJIRACLI-5\" --field \"customfield_10010\"",
  "--action getFieldValue --issue \"ZJIRACLI-5\" --field \"custom three\"",
  "--action getFieldValue --issue \"ZJIRACLI-5\" --field \"custom-versions\" --asVersion",
  "--action getFieldValue --issue \"ZJIRACLI-5\" --field \"custom-versions\" --suppressId",
  "--action getFieldValue --issue \"ZJIRACLI-5\" --field \"duedate\"",
  "--action getFieldValue --issue \"ZJIRACLI-5\" --field \"duedate\" --dateFormat \"yyyy-MM-dd\"",
  "--action getFieldValue --issue \"ZJIRACLI-5\" --field \"duedate\" --dateFormat \"yyyy.MM.dd\"",
  "--action getFieldValue --issue \"ZJIRACLI-5\" --field \"originalEstimate\"",
  "--action getFieldValue --issue \"ZJIRACLI-5\" --field \"parent\"",
  "--action getFieldValue --issue \"ZJIRACLI-5\" --field \"TIMEESTIMATE\"",
  "--action getFieldValue --issue \"ZJIRACLI-5\" --field \"timespent\"",
  "--action getFieldValue --issue \"ZJIRACLI-8\" --field \"labels\"",
  "--action getFieldValue --issue \"ZJIRACLIX-1\" --field \"assignee\"",
  "--action getFieldValue --issue \"ZJIRACLIX-2\" --field \"assignee\"",
  "--action getFieldValue --issue \"ZSUB-3\" --field \"testcase1\"",
  "--action getFieldValue --issue \"ZSUB-4\" --field \"environment\"",
  "--action getFilter --id \"24903\"",
  "--action getFilterList",
  "--action getGroupList",
  "--action getGroupList --regex \"jira.*\"",
  "--action getIssueHistoryList --issue \"ZHISTORY-1\"",
  "--action getIssueHistoryList --issue \"ZHISTORY-1\" --dateFormat \"yyyy-MM-dd HH:mm:ss.SSS\"",
  "--action getIssue --issue \"ZAGILE-2\" --dateFormat \"yyyy-MM-dd HH:mm:ss.SSS\" --outputFormat 2 --suppressId",
  "--action getIssue --issue \"ZCLICLONE-6\" --outputFormat 999",
  "--action getIssue --issue \"ZCUSTOM-2\"",
  "--action getIssue --issue \"ZCUSTOM-3\"",
  "--action getIssue --issue \"ZCUSTOM-6\" --dateFormat \"yyyy-MM-dd\"",
  "--action getIssue --issue \"ZCUSTOM-7\"",
  "--action getIssue --issue \"ZCUSTOM-7\" --dateFormat \"yyyy-MM-dd\"",
  "--action getIssue --issue \"ZFIELDS-3\"",
  "--action getIssue --issue \"ZFIELDS-4\" --suppressId",
  "--action getIssue --issue \"ZJIRACLI-12\"",
  "--action getIssue --issue \"ZJIRACLI-13\"",
  "--action getIssue --issue \"ZJIRACLI-3\" --dateFormat \"M/dd/yyyy HH:mm:ss\" --outputFormat 2 --suppressId",
  "--action getIssue --issue \"ZJIRACLI-3\" --dateFormat \"yyyy.MM.dd 'special format' HH:mm:ss z\"\"\" --outputFormat 2",
  "--action getIssue --issue \"ZJIRACLI-3\" --outputFormat 2",
  "--action getIssue --issue \"ZJIRACLI-5\" --field \"assignee\"",
  "--action getIssue --issue \"ZJIRACLI-5\" --outputFormat \"2\"",
  "--action getIssue --issue \"ZJIRACLI-8\" --outputFormat \"2\"",
  "--action getIssue --issue \"ZJIRACLIB-2\"",
  "--action getIssue --issue \"ZJIRACLIB-2\" --dateFormat \"yyyy.MM.dd 'special format' HH:mm:ss z\"\"\"",
  "--action getIssue --issue \"ZLINKS-1\" --outputFormat 2",
  "--action getIssue --issue \"ZSUB-1\" --suppressId",
  "--action getIssue --issue \"ZSUB-2\" --suppressId",
  "--action getIssue --issue \"ZUSER-1\"",
  "--action getIssue --issue \"ZWORK-1\" --outputFormat 2",
  "--action getIssue --issue \"ZWORK-2\" --outputFormat 2",
  "--action getIssueList --file \"target/output/jiracliclone/getIssueListChangeType.txt\" --jql \"project = ZCLICLONEX and type = 'improvement'\"",
  "--action getIssueList --file \"target/output/jiracli/getIssueListAllFieldsExceptCustom.txt\" --jql \"project = 'zjiracli'\" --outputFormat 998",
  "--action getIssueList --file \"target/output/jiracli/getIssueListAllFields.txt\" --jql \"project = 'zjiracli'\" --outputFormat 999",
  "--action getIssueList --file \"target/output/jiracli/getIssueListChangeType.txt\" --jql \"project = zjiracliA and type = 'improvement'\"",
  "--action getIssueList --file \"target/output/jiracli/getIssueListOutputFormat200.txt\" --jql \"project = 'zjiracli'\" --outputFormat 200",
  "--action getIssueList --file \"target/output/jiracli/getIssueListSearch.txt\" --jql \"project = zjiracli or project = zjiracliX\"",
  "--action getIssueList --file \"target/output/jiracli/getIssueList.txt\" --filter \"all\"",
  "--action getIssueList --filter \"all\" --outputFormat 2 --limit 75",
  "--action getIssueList --jql \"issuetype in subTaskIssueTypes() and parent = ZJIRACLI-3\"",
  "--action getIssueList --jql \"issue = ZJIRACLIB-2\" --outputFormat 2",
  "--action getIssueList --jql \"issue = ZJIRACLIB-2\" --outputFormat 3",
  "--action getIssueList --jql \"issue = ZVOTEWATCH-1 and watcher = 'user' and watcher = 'developer'\"",
  "--action getIssueList --jql \"issue = ZVOTEWATCH-1 and (watcher = 'user' or watcher = 'developer')\"",
  "--action getIssueList --jql \"issue = ZWORK-1\" --outputFormat 5",
  "--action getIssueList --jql \"key = ZCUSTOM-4\" --outputFormat \"2\" --columns \"testcase1,testcase2,key,summary,labels,Subtasks,Business Value,custom three,custom-group-picker,custom-multi-user-picker,custom-user-picker,custom-versions,custom-multi-select,Story Points,testcase1,testcase2,last comment\"",
  "--action getIssueList --jql \"key = ZCUSTOM-4\" --outputFormat \"4\" --columns \"testcase1,testcase2,key,summary,labels,Subtasks,Business Value,custom three,custom-group-picker,custom-multi-user-picker,custom-user-picker,custom-versions,custom-multi-select,Story Points,testcase1,testcase2,last comment\"",
  "--action getIssueList --jql \"key = ZCUSTOM-4\" --outputFormat \"5\" --columns \"testcase1,testcase2,key,summary,labels,Subtasks,Business Value,custom three,custom-group-picker,custom-multi-user-picker,custom-user-picker,custom-versions,custom-multi-select,Story Points,testcase1,testcase2,last comment\"",
  "--action getIssueList --jql \"key = ZCUSTOM-4\" --outputFormat \"999\" --columns \"testcase1,testcase2,key,summary,labels,Subtasks,Business Value,custom three,custom-group-picker,custom-multi-user-picker,custom-user-picker,custom-versions,custom-multi-select,Story Points,testcase1,testcase2,last comment\"",
  "--action getIssueList --jql \"parent = ZCLICLONE-11 and summary ~ 'Subtask 1'\"",
  "--action getIssueList --jql \"project = ZCLICLONEX and type = 'improvement'\" --limit 1",
  "--action getIssueList --jql \"project = ZCLICLONEZ and issuetype in subTaskIssueTypes()\"",
  "--action getIssueList --jql \"project = 'zcustom'\" --outputFormat 999",
  "--action getIssueList --jql \"project = zjiracliA and type = 'improvement'\" --limit 2",
  "--action getIssueList --jql \"project = 'zjiracli' and labels != null\" --outputFormat 999",
  "--action getIssueList --jql \"project = 'zjiracli' order by key desc\" --outputFormat 4 --dateFormat \"yyyy-MM-dd\"",
  "--action getIssueList --jql \"project = 'zjiracli'\" --outputFormat 999 --columns \"key,2,custom1,custom2,description,\"",
  "--action getIssueList --jql \"project = 'zjiracli'\" --outputFormat 999 --dateFormat \"yyyy.MM.dd\" --columns \"key,created,last comment user, last comment date, last comment\"",
  "--action getIssueList --jql \"project = zlinks and issue in linkedIssues(ZLINKS-1, 'duplicates')\"",
  "--action getIssueList --jql \"project = zlinks and issue in linkedIssues(ZLINKS-1, 'duplicates')\" --outputFormat 999",
  "--action getIssueList --jql \"project = 'zlinks'\" --outputFormat 998 --dateFormat \"yyyy-MM-dd\"",
  "--action getIssueList --jql \"project = ZRUNNER and labels = 'fieldValues'\" --outputFormat 2",
  "--action getIssueList --project \"ZAGILEC\" --dateFormat \"yyyy-MM-dd HH:mm:ss.SSS\" --outputFormat 2 --suppressId --columns \"Key,Summary,Epic Link\"",
  "--action getIssueList --project \"zjiracli\" --file \"target/output/jiracli/getIssueListProject.txt\" --outputFormat 101",
  "--action getIssueList --search \"key = ZCUSTOM-4\" --outputFormat \"2\" --columns \"testcase1,testcase2,key,summary,labels,Subtasks,Business Value,custom three,custom-group-picker,custom-multi-user-picker,custom-user-picker,custom-versions,custom-multi-select,Story Points,testcase1,testcase2,last comment\"",
  "--action getIssueList --search \"key = ZCUSTOM-4\" --outputFormat \"4\" --columns \"testcase1,testcase2,key,summary,labels,Subtasks,Business Value,custom three,custom-group-picker,custom-multi-user-picker,custom-user-picker,custom-versions,custom-multi-select,Story Points,testcase1,testcase2,last comment\"",
  "--action getIssueList --search \"key = ZCUSTOM-4\" --outputFormat \"5\" --columns \"testcase1,testcase2,key,summary,labels,Subtasks,Business Value,custom three,custom-group-picker,custom-multi-user-picker,custom-user-picker,custom-versions,custom-multi-select,Story Points,testcase1,testcase2,last comment\"",
  "--action getIssueList --search \"key = ZCUSTOM-4\" --outputFormat \"999\" --columns \"testcase1,testcase2,key,summary,labels,Subtasks,Business Value,custom three,custom-group-picker,custom-multi-user-picker,custom-user-picker,custom-versions,custom-multi-select,Story Points,testcase1,testcase2,last comment\"",
  "--action getIssue --project \"ZCLICLONE\" --issue \"ZCLICLONE-15\"",
  "--action getIssue --project \"ZCLICLONE\" --issue \"ZCLICLONE-2\"",
  "--action getIssueSecuritySchemeList",
  "--action getIssueSecuritySchemeList --options \"deleteEnabled\"",
  "--action getIssueTypeList",
  "--action getIssueTypeList --project \"@all\"",
  "--action getIssueTypeList --project \"ZPROJECT\"",
  "--action getIssueTypeSchemeList",
  "--action getIssueTypeSchemeList --options \"deleteEnabled\"",
  "--action getIssueTypeScreenSchemeList",
  "--action getIssueTypeScreenSchemeList --options \"deleteEnabled\"",
  "--action getLinkList --issue \"ZLINKS-1\"",
  "--action getLinkList --issue \"ZLINKS-1\" --regex \"duplicate\"",
  "--action getLinkList --issue \"ZLINKS-2\"",
  "--action getLinkList --jql \"parent = ZLINKS-1 or key = ZLINKS-1 order by key\"",
  "--action getLinkTypeList",
  "--action getLoginInfo --dateFormat \"yyyy-MM-dd HH:mm:ss\"",
  "--action getNotificationSchemeList",
  "--action getNotificationSchemeList --options \"deleteEnabled\"",
  "--action getPermissionSchemeList",
  "--action getPermissionSchemeList --options \"deleteEnabled\"",
  "--action getProjectCategoryList",
  "--action getProjectList --category \"\" --regex \"ZPROJECT.*\" --columns \"key\"",
  "--action getProjectList --file \"target/output/jiracli/getProjectListClone.txt\" --outputFormat 2",
  "--action getProjectList --file \"target/output/jiracliproject/getProjectList.txt\"",
  "--action getProjectList --lead \"developer\" --lookup --regex \"ZPROJECT.*\"",
  "--action getProjectList --regex \"ZPROJECT\" --outputFormat 999",
  "--action getProject --project \"ZCLICLONET\"",
  "--action getProject --project \"ZCLICLONEX\"",
  "--action getProject --project \"ZCLICLONEY\"",
  "--action getProject --project \"zjiracli\"",
  "--action getProject --project \"zjiracliD\"",
  "--action getProject --project \"zjiracliX\"",
  "--action getProject --project \"zjiracliX\" --suppressId",
  "--action getProject --project \"ZPROJECT\"",
  "--action getProject --project \"ZPROJECTX\"",
  "--action getProjectRoleActorList --project \"zjiracliB\" --role \"users\"",
  "--action getProjectRoleActorList --project \"ZROLES\" --role \"@all\" --outputFormat 2",
  "--action getProjectRoleActorList --project \"ZROLES\" --role \"users\"",
  "--action getProjectRoleByUserList --userId \"@all\" --columns \"User,Project,Administrators,Developers,Users,View\" --regex \"ZROLES\"",
  "--action getProjectRoleByUserList --userId \"automation\" --columns \"User,Project,Administrators,Developers,Users,View\" --regex \"ZROLES.*\"",
  "--action getProjectRoleList",
  "--action getProjectRoleList --regex \"zAdd project role test.*\"",
  "--action getScreenList",
  "--action getScreenList --options \"deleteEnabled\"",
  "--action getScreenList --regex \"(?i).*default.*\"",
  "--action getScreenSchemeList",
  "--action getScreenSchemeList --options \"deleteEnabled\"",
  "--action getSecurityLevelList --project \"zjiracli\"",
  "--action getSecurityLevelList --project \"zjiracliB\"",
  "--action getServerInfo --dateFormat \"yyyy-MM-dd\"",
  "--action getServerInfo --debug",
  "--action getServerInfo --outputFormat 2 --dateFormat \"yyyy-MM-dd HH:mm\"",
  "--action getServerInfo --outputFormat 999",
  "--action getStatusList",
  "--action getStatusList --project \"zjiracli\"",
  "--action getTransitionList --issue \"ZJIRACLI-3\"",
  "--action getTransitionList --issue \"ZJIRACLI-3\" --outputFormat 2",
  "--action getUserList --group \"jira-users\" --regex \"testuser1\" --outputFormat 999",
  "--action getUserList --group \"testgroup2\"",
  "--action getUserList --group \"testgroup2\" --outputFormat 2",
  "--action getUserList --name \"@all\"",
  "--action getUserList --name \"@all\" --regex \".*@x.com\"",
  "--action getUserList --name \"testuser\" --outputFormat 1",
  "--action getUserList --name \"testuser\" --outputFormat 2",
  "--action getUserList --project \"zuser\" --role \"developers\"",
  "--action getUser --userId \"Testuser3\"",
  "--action getUser --userKey \"testuser3\"",
  "--action getVersionList --project \"zjiracli\"",
  "--action getVersionList --project \"zjiracli\" --outputFormat 2",
  "--action getVersionList --project \"zjiracli\" --outputFormat 999 --dateFormat \"yyyy.MM.dd\"",
  "--action getVersion --project \"zjiracliA\" --version \"V1\" --dateFormat \"yyyy.MM.dd\"",
  "--action getVersion --project \"zjiracliC\" --version \"V2\" --outputFormat 999",
  "--action getVersion --project \"zjiracli\" --name \"V1\" --dateFormat \"yyyy MM dd\"",
  "--action getVersion --project \"zjiracli\" --version \"auto2\" --dateFormat \"yyyy.MM.dd\"",
  "--action getVersion --project \"zjiracli\" --version \"V2\" --dateFormat \"yyyy.MM.dd\"",
  "--action getVersion --project \"zjiracli\" --version \"With Blanks\"",
  "--action getVoterList --issue \"ZVOTEWATCH-1\"",
  "--action getVoterList --issue \"ZVOTEWATCH-1\" --outputFormat 2",
  "--action getVoterList --issue \"ZVOTEWATCH-1\" --outputFormat 999",
  "--action getWatcherList --issue \"ZVOTEWATCH-1\"",
  "--action getWatcherList --issue \"ZVOTEWATCH-1\" --outputFormat 2",
  "--action getWatcherList --issue \"ZVOTEWATCH-1\" --outputFormat 999",
  "--action getWorkflowList --dateFormat \"yyyy-MM-dd\" --regex \"(Agile Simplified)|(jira)\"",
  "--action getWorkflow --workflow \"Agile Simplified\" --dateFormat \"yyyy-MM-dd\"",
  "--action getWorkList --issue \"ZWORK-1\"",
  "--action getWorkList --issue \"ZWORK-1\" --dateFormat \"yyyy-MM-dd HH:mm:ss.SSS\"",
  "--action import --file \"src/itest/resources/importProjects.json\" --options \"logFile=-\"",
  "--action linkIssue --issue \"249453\" --toIssue \"249454\" --link \"10011\" --comment \"Link comment\"",
  "--action linkIssue --issue \"ZCLICLONE-4\" --toIssue \"ZCLICLONE-1\" --link \"relates\"",
  "--action linkIssue --issue \"ZLINKS-1\" --toIssue \"ZLINKS-2\" --link \"relates\" --comment \"Link comment\"",
  "--action linkIssue --issue \"ZLINKS-1\" --toIssue \"ZLINKS-2\" --link \"relates\" --comment \"Link comment with group\" --group \"jira-users\"",
  "--action linkIssue --issue \"ZLINKS-1\" --toIssue \"ZLINKS-2\" --link \"relates\" --comment \"Link comment with role and group\" --role \"Developers\" --group \"jira-users\"",
  "--action linkIssue --issue \"ZLINKS-1\" --toIssue \"ZLINKS-2\" --link \"relates\" --comment \"Link comment with role\" --role \"Developers\"",
  "--action linkIssue --issue \"ZLINKS-1\" --toIssue \"ZLINKS-3\" --link \"duplicate\" --verbose",
  "--action linkIssue --issue \"ZLINKS-1\" --toIssue \"ZLINKS-3\" --link \"relates\"",
  "--action linkIssue --issue \"ZSUB-1\" --toIssue \"ZSUB-2\" --link \"relates\"",
  "--action login --outputFormat 2 --dateFormat \"yyyy-MM-dd HH:mm:ss\"",
  "--action login > target/output/jiracliinfo/login.txt",
  "--action logout -l < target/output/jiracliinfo/login.txt",
  "--action modifyFieldValue --issue \"ZFIELDS-4\" --field \"fixVersions\" --field2 \"components\" --findReplace \"'V2:V3,V4', C1:C2\" --autoVersion --autoComponent",
  "--action modifyFieldValue --issue \"ZFIELDS-4\" --field \"summary\" --field2 \"environment\" --findReplace \"original:modified\"",
  "--action releaseVersion --project \"zjiracli\" --name \"V1\" --continue",
  "--action releaseVersion --project \"zjiracli\" --name \"V1\" --dateFormat \"yyyy.MM.dd\" --description \"V1 description released\"",
  "--action removeAttachment --issue \"ZATTACH-1\" --id \"63115\"",
  "--action removeAttachment --issue \"ZATTACH-1\" --name \"data.txt\"",
  "--action removeCustomField --field \"22507\" --continue",
  "--action removeCustomField --field \"customfield_22509\" --continue",
  "--action removeCustomField --field \"zzimport1\" --type \"com.atlassian.jira.plugin.system.customfieldtypes:textfield\" --continue",
  "--action removeCustomField --field \"zzz_Select List (single choice)\" --continue",
  "--action removeGroup --group \"bad\"",
  "--action removeGroup --group \"Testgroup1\"",
  "--action removeGroup --group \"testgroup2\"",
  "--action removeLabels --issue \"ZJIRACLI-8\" --labels \"addLabel1 addLabel2\"",
  "--action removeLabels --issue \"ZJIRACLI-9\" --labels \"xxx\"",
  "--action removeProjectRoleActors --project \"zjiracli\" --role \"users\" --userId \"user, admin\"",
  "--action removeProjectRoleActors --project \"ZROLES\" --role \"users\" --userId \"user, admin\"",
  "--action removeProjectRoleActors --project \"ZROLESX\" --role \"users\" --userId \"user, admin\"",
  "--action removeProjectRole --name \"zAdd project role test\" --continue",
  "--action removeProjectRole --name \"zAdd project role test updated\" --continue",
  "--action removeUser --userId \"BAD\"",
  "--action removeUser --userId \"testuser1\"",
  "--action removeUser --userId \"testuser1New\"",
  "--action removeUser --userId \"testuser2\"",
  "--action removeUser --userId \"Testuser3\"",
  "--action removeVote --issue \"ZVOTEWATCH-1\" --user \"developer\" --password \"asDeVqeTwsjtr4GnyKwf\"",
  "--action removeWatchers --issue \"ZVOTEWATCH-1\" --userId \"invalid, xxxxxx\" --continue",
  "--action removeWatchers --issue \"ZVOTEWATCH-1\" --userId \"user, developer\"",
  "--action removeWork --issue \"ZWORK-1\" --id \"32811\"",
  "--action renderRequest --file \"target/output/jiracli/renderRequestInvalidType.txt\" --type \"INVALID\" --verbose",
  "--action renderRequest --issue \"ZJIRACLI-3\" --file \"target/output/jiracli/renderRequest.txt\"",
  "--action renderRequest --project \"zjiracli\" --file \"target/output/jiracli/verifyProjectIssueTypeScreenScheme.txt\" --request \"plugins/servlet/project-config/ZJIRACLI/summary\"",
  "--action renderRequest --project \"zjiracli\" --file \"target/output/jiracli/verifyUpdateProjectIssueTypeScreenSchemeDefault.txt\" --request \"plugins/servlet/project-config/ZJIRACLI/summary\"",
  "--action renderRequest --request \"/rest/project-templates/1.0/templates\" --type \"FORM_URL_ENCODED\" --acceptType \"JSON\" --verbose",
  "--action run",
  "--action run --common \"--issue ZSUB-4\"",
  "--action run --file \"-\"",
  "--action run --file \"src/itest/resources//renderRequest.txt\" --findReplace \"@project@:zjiracli\"",
  "--action run --file \"src/itest/resources/runReplaceMapReference.txt\" --common \"--project ZRUNNER --labels JCLI528\"",
  "--action run --file \"src/itest/resources/runReplaceMap.txt\" --common \"--project ZRUNNER\"",
  "--action run --file \"src/itest/resources/run.txt\"",
  "--action run --file \"src/itest/resources/runWithFindReplace.txt\" --findReplace \"##action##:getServerInfo\"",
  "--action run --file \"target/output/jiracliexport2/exportDataProject.txt\" --findReplace \"--project ZEXPORT2:--project ZEXPORT2E\" --findReplaceRegex \"--name [^-]*:\"",
  "--action runFromAttachmentList --issue \"ZRUNNER-1\" --common \"-a getAttachment --file \"\"target/output/jiraclirunner/Attachment-@attachment@\"\" --name @attachmentId@ --issue ZRUNNER-1\"",
  "--action runFromAttachmentList --issue \"ZRUNNER-1\" --common \"-a getAttachment --file \"\"target/output/jiraclirunner/Attachment-@attachment@\"\" --name @attachment@ --issue ZRUNNER-1\"",
  "--action runFromComponentList --project \"ZRUNNER\" --common \"-a getComponent --project ZRUNNER --version \"\"@component@\"\"\" --continue",
  "--action runFromCsv --file \"src/itest/resources/createUpdate.csv\" --common \"--project ZRUNNER\"",
  "--action runFromCsv --file \"src/itest/resources/import2.csv\" --propertyFile \"src/itest/resources/import.properties\" --common \"--project ZRUNNER --action createIssue\" --continue",
  "--action runFromCsv --file \"src/itest/resources/import.csv\" --propertyFile \"src/itest/resources/import.properties\" --common \"--project ZRUNNER\" --continue",
  "--action runFromCsv --file \"src/itest/resources/run2.csv\" --common \"-a createIssue --project ZRUNNER\"",
  "--action runFromCsv --file \"src/itest/resources/run.csv\" --findReplace \"@project@:ZRUNNER\"",
  "--action runFromCsv --file \"src/itest/resources/runFieldValues.csv\" --common \"--project ZRUNNER --action createIssue --type bug --summary xxx\" --continue",
  "--action runFromCsv --file \"src/itest/resources//runIgnoreFields.csv\" --propertyFile \"src/itest/resources//runIgnoreFields.properties\" --common \"--project ZRUNNER --action createIssue\"",
  "--action runFromCsv --file \"src/itest/resources/runsimple.csv\" --common \"--action getProject\"",
  "--action runFromCsv --file \"src/itest/resources/runUsingProperties.csv\" --propertyFile \"src/itest/resources/runUsingProperties.properties\" --common \"-a createIssue --project ZRUNNER\"",
  "--action runFromFieldConfigurationList --limit 2 --special \"    #\" --common \"--action getClientInfo --reference @: @fieldConfiguration@# \"",
  "--action runFromFieldConfigurationSchemeList --limit 2 --special \"    #\" --common \"--action getClientInfo --reference @: @scheme@# \"",
  "--action runFromFieldConfigurationSchemeList --regex \"ZCOPY\" --common \"--action deleteFieldConfigurationScheme --id @schemeId@\" --options \"deleteEnabled\" --limit 10",
  "--action runFromGroupList --regex \"group number .*\" --common \"-a removeGroup --group ~@group@~\" --special \"    ~\"",
  "--action runFromGroupList --regex \"jira.*\" --limit 1 --common \"-a getServerInfo --comment ~group: @group@~\" --special \"    ~\"",
  "--action runFromIssueList --common '--action cloneIssue --issue @issue@ --toProject ZRUNNERC --description \"Bulk clone example\" ' --search 'project = ZRUNNER and summary ~ \"volume-*\"'",
  "--action runFromIssueList --common \"--action deleteIssue --issue @issue@  \" --search 'project = ZRUNNER and summary ~ \"volume-*\"'",
  "--action runFromIssueList --file \"-\" --jql \"project = 'zjiracli' and labels != null\" --common \"--action addLabels\"",
  "--action runFromIssueList --file \"-\" --jql \"project = 'zjiracli' and labels != null\" --common \"--issue @issue@\" --findReplace \"##label##:done-by-action\"",
  "--action runFromIssueList --jql \"issuetype = Sub-task\" --common \"-a getIssue --issue @parent@ --comment issue:@issue@,id:@issueId@,project:@project@,projectId:@projectId@,parent:@parent@,parentId:@parentId@\" --limit 1",
  "--action runFromIssueList --jql \"labels in (JCLI528)\" --common \"-a getIssue --issue @issue@ --outputFormat 999\"",
  "--action runFromIssueList --jql \"project in (ZJIRACLI)\" --common \"-a getAttachmentList --outputFormat 999 --issue \"\"@issue@\"\" --file target/output/jiracliproject/attachmentList.csv --append\" --continue",
  "--action runFromIssueList --jql \"project in (ZJIRACLI)\" --common \"-a getLinkList --issue \"\"@issue@\"\" --file target/output/jiracliproject/linkList.csv --append\" --continue",
  "--action runFromIssueList --jql \"project in (ZJIRACLI, ZHISTORY)\" --common \"-a getIssueHistoryList --issue \"\"@issue@\"\" --file target/output/jiracliproject/historyList.csv --dateFormat: yyyy-MM-dd_HH:mm:ss.SSS --append\" --continue",
  "--action runFromIssueList --jql \"project in (ZWORK)\" --common \"-a getWorkList --outputFormat 999 --issue \"\"@issue@\"\" --file target/output/jiracliwork/workList.csv --append\" --continue",
  "--action runFromIssueList --jql \"project = 'zjiracli' and labels != null\" --common \"--action addLabels --issue @issue@ --labels done-by-action\"",
  "--action runFromIssueSecuritySchemeList --limit 2 --special \"    #\" --common \"--action getClientInfo --reference @: @scheme@# \"",
  "--action runFromIssueSecuritySchemeList --regex \"ZCOPY\" --common \"--action deleteIssueSecurityScheme --id @schemeId@\" --options \"deleteEnabled\" --limit 10",
  "--action runFromIssueTypeSchemeList --limit 2 --special \"    #\" --common \"--action getClientInfo --reference @: @scheme@# \"",
  "--action runFromIssueTypeSchemeList --regex \"ZCOPY\" --common \"--action deleteIssueTypeScheme --id @schemeId@\" --options \"deleteEnabled\" --limit 10",
  "--action runFromIssueTypeScreenSchemeList --limit 2 --special \"    #\" --common \"--action getClientInfo --reference @: @scheme@# \"",
  "--action runFromIssueTypeScreenSchemeList --regex \"ZCOPY\" --common \"--action deleteIssueTypeScreenScheme --id @schemeId@\" --options \"deleteEnabled\" --limit 10",
  "--action runFromLinkList --jql \"parent = ZLINKS-1 or key = ZLINKS-1 order by key\" --common \"-a getClientInfo --options ~from: @fromIssue@, to: @toIssue@, type: @linkType@, typeId: @linkTypeId@, description: @linkDescription@, id: @linkId@~\" --special \"    ~\"",
  "--action runFromLinkList --options \"outward\" --regex \"relates\" --jql \"parent = ZLINKS-1 or key = ZLINKS-1 order by key\" --common \"-a getClientInfo --options ~from: @fromIssue@, to: @toIssue@, type: @linkType@, typeId: @linkTypeId@, description: @linkDescription@, id: @linkId@~\" --special \"    ~\"",
  "--action runFromList --list \"1, 2, 3\" --common \"--action createIssue --project ZRUNNER --type task --summary volume-@entry@ \"",
  "--action runFromList --list \"aaa\" --common \"--action getServerInfo\" --debug",
  "--action runFromList --list \"A,B\" --common \"-a getProject --project ZRUNNER --cookies target/output/jiraclirunner/cookiesBoth.txt -v\" --cookies \"target/output/jiraclirunner/parentCookiesBoth.txt\" --verbose",
  "--action runFromList --list \"A,B\" --common \"-a getProject --project ZRUNNER --cookies target/output/jiraclirunner/cookies.txt -v\" --verbose",
  "--action runFromList --list \"A,B\" --common \"-a getProject --project ZRUNNER -v\" --cookies \"target/output/jiraclirunner/parentCookies.txt\" --verbose",
  "--action runFromList --list \"a\" --common \"--issue ZSUB-4 --action setFieldValue --field environment --value \"\"%original_description%\"\"\"",
  "--action runFromList --list \"Client, Server\" --common \"-a get@entry@Info\"",
  "--action runFromList --list \"custom, Default Issue Type Scheme, custom,\" --continue --common '-a updateProject --project ZRUNNER --issueTypeScheme \"@entry@\"'",
  "--action runFromList --list \"NOT_FOUND, ZRUNNER\" --common \"-a getProjectList --regex @entry@ --append -f target/output/jiraclirunner/runFromListAppend.txt\" --clearFileBeforeAppend",
  "--action runFromList --list \"xxx, yyy\" --common \"--action runFromProjectList --regex ~(?i)jira|ZRUNNER~ --common ~--action getProject --project @project@ --comment @entry@ ~\" --special \"    ~\"",
  "--action runFromNotificationSchemeList --limit 2 --special \"    #\" --common \"--action getClientInfo --reference @: @scheme@# \"",
  "--action runFromNotificationSchemeList --regex \"ZCOPY\" --common \"--action deleteNotificationScheme --id @schemeId@\" --options \"deleteEnabled\" --limit 10",
  "--action runFromPermissionSchemeList --limit 2 --special \"    #\" --common \"--action getClientInfo --reference @: @scheme@# \"",
  "--action runFromPermissionSchemeList --regex \"ZCOPY\" --common \"--action deletePermissionScheme --id @schemeId@\" --options \"deleteEnabled\" --limit 10",
  "--action runFromProjectList --category \"another\" --common \"-a getProject --project @project@\"",
  "--action runFromProjectList --common \"-a getProject --project \"\"@projectId@\"\"\" --continue --regex \"ZRUNNER\"",
  "--action runFromProjectList --common \"-a getProject --project \"\"@project@\"\"\" --limit 5 --continue",
  "--action runFromProjectList --lead \"developer\" --regex \"ZPROJECT.*\" --common \"-a getProject --project @project@\"",
  "--action runFromProjectList --regex \"ZJIRACLI.*|ZPROJECT\" --common \"-a getComponentList --outputFormat 999 --project \"\"@project@\"\" --file target/output/jiracliproject/componentList.csv --append\" --continue",
  "--action runFromProjectList --regex \"ZJIRACLI.*|ZPROJECT\" --common \"-a getIssueTypeList --project \"\"@project@\"\" --file target/output/jiracliproject/issueTypeList.csv --append\" --continue",
  "--action runFromProjectList --regex \"ZJIRACLI.*|ZPROJECT\" --common \"-a getSecurityLevelList --outputFormat 999 --project \"\"@project@\"\" --file target/output/jiracliproject/securityLevelList.csv --append\" --continue",
  "--action runFromProjectList --regex \"ZJIRACLI.*|ZPROJECT\" --common \"-a getVersionList --outputFormat 999 --project \"\"@project@\"\" --file target/output/jiracliproject/versionList.csv --append\" --continue",
  "--action runFromScreenList --limit 2 --special \"    #\" --common \"--action getClientInfo --reference @: @screen@# \"",
  "--action runFromScreenSchemeList --limit 2 --special \"    #\" --common \"--action getClientInfo --reference @: @scheme@# \"",
  "--action runFromScreenSchemeList --regex \"ZCOPY\" --common \"--action deleteScreenScheme --id @schemeId@\" --options \"deleteEnabled\" --limit 10",
  "--action runFromUserList --name \"@all\" --limit 2 --regex \"((admin)|(automation))\" --common \"--action getServerInfo --comment @userId@\"",
  "--action runFromVersionList --project \"ZRUNNER\" --common \"-a getVersion --project @projectId@ --version \"\"@versionId@\"\"\" --continue --regex \"V1\"",
  "--action runFromVersionList --project \"ZRUNNER\" --common \"-a getVersion --project ZRUNNER --version \"\"@version@\"\"\" --continue",
  "--action runFromWorkflowList --regex \"((jira)|(Agile Simplified))\" --limit 2 --file \"-\"",
  "--action runFromWorkflowSchemeList --regex \".*Simplified.*\" --limit 2 --file \"-\"",
  "--action runFromWorkflowSchemeList --regex \"ZCLICLONE.*\" --common \"--action deleteWorkflowScheme --id @schemeId@\" --continue",
  "--action setFieldValue --issue \"ZCUSTOM-1\" --field \"custom-cascade-select\" --values \"1 - A\"",
  "--action setFieldValue --issue \"ZCUSTOM-1\" --field \"custom-cascade-select\" --values \"2,B\" --asCascadeSelect",
  "--action setFieldValue --issue \"ZCUSTOM-4\" --field \"custom-multi-select\" --values \"s1,s2,s3\"",
  "--action setFieldValue --issue \"ZCUSTOM-7\" --field \"Story Points\" --value \"\"",
  "--action setFieldValue --issue \"ZFIELDS-1\" --field \"custom1\" --values \"The following should be on a new line: \\n XXX\"",
  "--action setFieldValue --issue \"ZFIELDS-1\" --field \"custom1\" --values \"'xxx,yyy'\"",
  "--action setFieldValue --issue \"ZFIELDS-1\" --field \"custom1\" --values \"xxx,yyy\"",
  "--action setFieldValue --issue \"ZFIELDS-1\" --field \"custom1\" --value \"The following should be on a new line: \\n XXX\"",
  "--action setFieldValue --issue \"ZFIELDS-1\" --field \"custom1\" --value \"xxx,yyy\"",
  "--action setFieldValue --issue \"ZFIELDS-1\" --field \"custom-datetime\" --value \"21/10/1940 11:39:12\" --dateFormat \"dd/MM/yyyy HH:mm:ss\"",
  "--action setFieldValue --issue \"ZFIELDS-1\" --field \"environment\" --values \"\" --field2 \"custom1\" --values2 \"xxx\"",
  "--action setFieldValue --issue \"ZFIELDS-1\" --file \"src/itest/resources/data.txt\" --field \"environment\" --appendText",
  "--action setFieldValue --issue \"ZFIELDS-2\" --field \"custom1\" --values \"append text\" --appendText",
  "--action setFieldValue --issue \"ZFIELDS-2\" --field \"custom-group-picker\" --values \"jira-users\"",
  "--action setFieldValue --issue \"ZFIELDS-2\" --field \"custom-multi-group-picker\" --values \"jira-users,jira-administrators\"",
  "--action setFieldValue --issue \"ZFIELDS-2\" --field \"custom-multi-select\" --values \"s1,s2\"",
  "--action setFieldValue --issue \"ZFIELDS-2\" --field \"custom-multi-select\" --values \"s3\" --append",
  "--action setFieldValue --issue \"ZFIELDS-2\" --field \"custom-multi-user-picker\" --values \"automation\"",
  "--action setFieldValue --issue \"ZFIELDS-2\" --field \"custom-user-picker\" --values \"automation\"",
  "--action setFieldValue --issue \"ZFIELDS-2\" --file \"src/itest/resources/data.txt\" --field \"custom1\"",
  "--action setFieldValue --issue \"ZFIELDS-3\" --field \"description\" --verbose --value \"aaa\n bbb\"",
  "--action setFieldValue --issue \"ZFIELDS-3\" --field \"priority\" --verbose --value \"blocker\"",
  "--action setFieldValue --issue \"ZFIELDS-3\" --field \"reporter\" --verbose --value \"automation\"",
  "--action setFieldValue --issue \"ZFIELDS-3\" --field \"summary\" --verbose --value \"xxx\"",
  "--action setFieldValue --issue \"ZFIELDS-3\" --field \"type\" --verbose --value \"sub-task2\"",
  "--action setFieldValue --issue \"ZHISTORY-1\" --field \"custom-multi-select\" --values \"s1,s2\"",
  "--action setFieldValue --issue \"ZJIRACLI-3\" --field \"custom-labels\" --values \"aaa,bbb\"",
  "--action setFieldValue --issue \"ZJIRACLI-3\" --field \"custom-labels\" --values \"aaa, ccc\" --subtract",
  "--action setFieldValue --issue \"ZJIRACLI-3\" --field \"custom-labels\" --values \"bbb\" --subtract",
  "--action setFieldValue --issue \"ZJIRACLI-3\" --field \"custom-labels\" --values \"ccc\" --append",
  "--action setFieldValue --issue \"ZJIRACLI-5\" --field \"custom-versions\" --values \"autoAppend\" --asVersion --append --autoVersion",
  "--action setFieldValue --issue \"ZJIRACLI-5\" --field \"custom-versions\" --values \"V1, V2\" --asVersion",
  "--action setFieldValue --issue \"ZJIRACLI-5\" --field \"custom-versions\" --values \"V1, V2\" --asVersion --append",
  "--action setFieldValue --issue \"ZSUB-1\" --field \"custom-versions\" --value \"%original_fixVersions%\" --field2 \"description\" --values2 \"%original_description% - %original_fixVersions%\"",
  "--action setShareScope --value \"global\"",
  "--action transitionIssue --issue \"ZJIRACLI-3\" --transition \"5\" --resolution \"Fixed\" --fixVersions \"V1,  V2\" --comment \"I fixed this. \\n It will be good now.\" --type \"Bug\" --continue --priority \"Major\" --reporter \"automation\" --affectsVersions \"\" --environment \"\" --components \"\"",
  "--action transitionIssue --issue \"ZJIRACLI-3\" --transition \"Start Progress\"",
  "--action transitionIssue --issue \"ZSUB-3\" --transition \"Resolve Issue\" --field \"testcase1\" --values \"subtasks: %parent_subtasks%\" --comment \"subtasks: %parent_subtasks%\"",
  "--action unarchiveVersion --project \"zjiracli\" --name \"V1\"",
  "--action unreleaseVersion --project \"zjiracli\" --name \"V1\" --date \"2015.12.31\" --dateFormat \"yyyy.MM.dd\" --description \"V1 description\"",
  "--action updateComponent --project \"zjiracli\" --component \"C3First\" --name \"C3\" --description \"a generic description\" --lead \"automation\" --defaultAssignee \"project_lead\"",
  "--action updateComponent --project \"ZSUB\" --component \"C1\" --description \"C1 description\"",
  "--action updateComponent --project \"ZSUB\" --component \"C2\" --description \"C2 description\"",
  "--action updateFilter --id \"24903\" --jql \"project = ZFILTER AND resolution is EMPTY\" --favorite",
  "--action updateIssue --issue \"249564\" --fixVersions \"auto2\" --autoVersion --append",
  "--action updateIssue --issue \"ZCUSTOM-1\" --field \"custom-cascade-select\" --values \"1,A\" --asCascadeSelect",
  "--action updateIssue --issue \"ZCUSTOM-4\" --field \"custom-multi-select\" --values \"s1,s2,s3\"",
  "--action updateIssue --issue \"ZFIELDS-1\" --description \"append text\" --appendText",
  "--action updateIssue --issue \"ZHISTORY-1\" --summary \"Updated summary\" --description \"Updated description\" --field \"custom1\" --values \"updated value\"",
  "--action updateIssue --issue \"ZJIRACLI-3\" --affectsVersions \"swap1\" --fixVersions \"swap2\" --autoVersion",
  "--action updateIssue --issue \"ZJIRACLI-3\" --components \"auto1\" --autoComponent",
  "--action updateIssue --issue \"ZJIRACLI-3\" --components \"auto2\" --autoComponent --append",
  "--action updateIssue --issue \"ZJIRACLI-3\" --components \"swap1\" --autoComponent",
  "--action updateIssue --issue \"ZJIRACLI-3\" --custom \"custom1:zzz\"",
  "--action updateIssue --issue \"ZJIRACLI-3\" --custom \"{\\\"custom1\\\":\\\"zzz\\\"}\"",
  "--action updateIssue --issue \"ZJIRACLI-3\" --date \"27/Jan/10\" --dateFormat \"d/MMM/yy\"",
  "--action updateIssue --issue \"ZJIRACLI-3\" --date \"\" --components \"\" --affectsVersions \"\"",
  "--action updateIssue --issue \"ZJIRACLI-3\" --date \"\" --components \"\" --affectsVersions \"\" --fixVersions \"\"",
  "--action updateIssue --issue \"ZJIRACLI-3\" --environment \"x12345\" --originalEstimate \"3h\" --comment \"Added on updateIssue\"",
  "--action updateIssue --issue \"ZJIRACLI-3\" --fixVersions \"auto1\" --autoVersion",
  "--action updateIssue --issue \"ZJIRACLI-5\" --custom \"custom-versions:,\" --component \"\"",
  "--action updateIssue --issue \"ZJIRACLI-5\" --date \"\"",
  "--action updateIssue --issue \"ZJIRACLI-5\" --date \"2015*01*02\" --dateFormat \"yyyy*MM*dd\"",
  "--action updateIssue --issue \"ZJIRACLI-5\" --field \"custom1\" --values \"xxxx\"",
  "--action updateIssue --issue \"ZJIRACLI-5\" --field \"custom2\" --values \"\"",
  "--action updateIssue --issue \"ZJIRACLI-8\" --labels \"label2 label3 label2 label3\" --description \"labels added\"",
  "--action updateIssue --issue \"ZJIRACLIB-2\" --security \"\"",
  "--action updateIssue --issue \"ZJIRACLIB-2\" --security \"developer-role\"",
  "--action updateIssue --issue \"ZSUB-1\" --environment \"%original_description%\"",
  "--action updateIssue --issue \"ZUSER-1\" --reporter \"automation\"",
  "--action updateIssue --issue \"ZUSER-1\" --reporter \"testuser2\" --lookup",
  "--action updateIssue --issue \"ZWORK-2\" --estimate \"2w 1d\"",
  "--action updateIssue --issue \"ZWORK-2\" --estimate \"3w 1d\" --summary \"Updated\"",
  "--action updateIssue --issue \"ZWORK-2\" --originalEstimate \"4w 2d\"",
  "--action updateProject --project \"zjiracliC\" --issueSecurityScheme \"test restrictions\" --notificationScheme \"test\" --permissionScheme \"Restrict create issue\"",
  "--action updateProject --project \"zjiracli\" --issueTypeScheme \"10000\"",
  "--action updateProject --project \"zjiracli\" --issueTypeScheme \"Default Issue Type Scheme\"",
  "--action updateProject --project \"zjiracli\" --issueTypeScheme \"zclone\"",
  "--action updateProject --project \"zjiracli\" --issueTypeScreenScheme \"1\"",
  "--action updateProject --project \"zjiracli\" --issueTypeScreenScheme \"Copy of default\"",
  "--action updateProject --project \"zjiracli\" --issueTypeScreenScheme \"Default Issue Type Screen Scheme\"",
  "--action updateProject --project \"zjiracli\" --workflowScheme \"\" --issueTypeScheme \"\" --fieldConfigurationScheme \"\" --issueTypeScreenScheme \"\"",
  "--action updateProject --project \"zjiracliX\" --defaultAssignee \"project_lead\"",
  "--action updateProject --project \"zjiracliX\" --defaultAssignee \"unassigned\"",
  "--action updateProject --project \"zjiracliX\" --description \"Updated description again\"",
  "--action updateProject --project \"zjiracliX\" --description \"Updated description\" --issueSecurityScheme \"test restrictions\" --fieldConfigurationScheme \"Description required\" --notificationScheme \"test\" --verbose",
  "--action updateProject --project \"ZPROJECT\" --category \"\"",
  "--action updateProject --project \"ZPROJECT\" --category \"another\"",
  "--action updateProject --project \"ZPROJECT\" --notificationScheme \"\"",
  "--action updateProject --project \"ZPROJECT\" --notificationScheme 10000",
  "--action updateProject --project \"ZPROJECT\" --url \"https://bobswift-test.atlassian.net\"",
  "--action updateProjectRole --role \"zAdd project role test\" --name \"zAdd project role test updated\"",
  "--action updateUserProperty --userId \"testuser1\" --name \"a b\" --value \" xxxx\"",
  "--action updateUserProperty --userId \"testuser1\" --name \"testProperty\" --value \"test property value\"",
  "--action updateVersion --project \"zjiracliC\" --version \"V2\" --description \"NEW description\" --startDate \"2015-01-01\" --date \"2015-02-01\" --dateFormat \"yyyy-MM-dd\"",
  "--action updateVersion --project \"zjiracli\" --version \"auto1\" --after \"-1\"",
  "--action updateVersion --project \"zjiracli\" --version \"auto1\" --after \"auto2\"",
  "--action updateVersion --project \"zjiracli\" --version \"auto2\" --after \"\"",
  "--action updateVersion --project \"zjiracli\" --version \"auto2\" --date \"\" --dateFormat \"yyyy/MM/dd\"",
  "--action updateVersion --project \"zjiracli\" --version \"auto2\" --description \"updateVersion description\" --startDate \"2014/09/30\" --date \"2015/01/02/\" --dateFormat \"yyyy/MM/dd\"",
  "--action updateVersion --project \"zjiracli\" --version \"V1\" --description \"V1 description\"",
  "--action updateWork --issue \"ZWORK-1\" --id \"32811\" --comment \"Updated work log entry\"",
  "--action updateWork --issue \"ZWORK-1\" --id \"32811\" --timeSpent \"1w\" --autoAdjust",
  "--action updateWork --issue \"ZWORK-1\" --id \"32811\" --userId \"developer\"",
  "--action validateLicense"
]

gem_examples = []
EXAMPLES.each do |example|
  puts example
  split_example = example.gsub(/"([^"]*)"/) do |match|
    match.gsub(' ', '_SPACE_').gsub("\n", '_NEWLINE_')
  end.split(' ')

  rb_example = {}
  split_example.each_with_index do |substr, idx|
    if substr.starts_with?('--')
      sym = substr[2..-1].underscore.to_sym

      val = if idx == split_example.length-1 || split_example[idx+1].starts_with?('--')
        true
      elsif sym == :action
        split_example[idx+1].underscore.to_sym
      else
        str = split_example[idx+1].gsub('_SPACE_', ' ').gsub('_NEWLINE_', "\n")
        str = str[1..-1] if str.starts_with?('"')
        str = str[0..-2] if str.ends_with?('"')
        str
      end
      rb_example[sym] = val
    end
  end
  gem_examples << {cli_example: example, gem_example: rb_example}
end

File.open('examples.yml', 'w') {|f| f.write gem_examples.to_yaml }
ap gem_examples
